import { phonemes } from "./phonemes"

export const categories = {
    es: {
        word: 'Palabra',
        phoneme: 'Fonema',
        both: 'Palabra/Fonema'
    },
    en: {
        word: 'Word',
        phoneme: 'Phoneme',
        both: 'Word/Phoneme'
    }
}

export const dificulty = {
    es: [
        'Complejo',
        'Difícil',
        'Medio',
        'Sencillo'
    ],
    en: [
        'Complex',
        'Hard',
        'Medium',
        'Easy'
    ]
}

export const gestures = { 
    es: [
       {
            phonemes: 'a',
            spelling: phonemes['a'].associated,
            name: 'Saludo',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Con la punta de los dedos tocando la sien se extiende el brazo quedando horizontal a la altura del hombro',
        },
        {
            phonemes: 'óla',
            spelling: ['hola'],
            name: 'Saludo',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Con la punta de los dedos tocando la sien se extiende el brazo quedando horizontal a la altura del hombro',
        },
        {
            phonemes: 'e',
            spelling: phonemes['e'].associated,
            name: 'Agradecimiento',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Con la punta de los dedos tocando la barbilla se extiende completamente el brazo hacia el frente y a la altura del pecho',
        },
        {
            phonemes: 'gɾasias',
            spelling: ['gracias'],
            name: 'Agradecimiento',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Con la punta de los dedos tocando la barbilla se extiende completamente el brazo hacia el frente y a la altura del pecho',
        },
        {
            phonemes: 'o',
            spelling: phonemes['o'].associated,
            name: 'Circunferencia',
            nature: 'phoneme',
            category: 'phoneme',
            dificulty: 2,
            description: 'Con los dedos extendidos y apuntando hacia arriba se dibuja una circunferencia iniciando el recorrido hacia adentro (hacia al pecho).',
        },
        {
            phonemes: 'u',
            spelling: phonemes['u'].associated,
            name: 'Balanceo',
            nature: 'phoneme',
            category: 'phoneme',
            dificulty: 2,
            description: 'Partiendo de la altura de las costillas con el codo ligeramente más flexionado de 90 grados y los dedos apuntando al frente, se dibuja una depresión hacia la izquierda (como un tazón poco profundo) y se regresa con una depresión hacia la derecha',
        },
        {
            phonemes: 'p',
            spelling: phonemes['p'].associated,
            name: 'Doble golpe',
            nature: 'phoneme',
            category: 'both',
            dificulty: 2,
            description: 'Con la mano derecha en puño y a la altura del corazón, y la izquierda con la palma hacia arriba a la altura del ombligo, se baja la derecha golpeando dos veces en la mano izquierda y regresa a la altura original',
        },
        {
            phonemes: 'poɾ ké',
            spelling: ['¿Por qué?'],
            name: 'Doble golpe',
            nature: 'word',
            category: 'both',
            dificulty: 2,
            description: 'Con la mano derecha en puño y a la altura del corazón, y la izquierda con la palma hacia arriba a la altura del ombligo, se baja la derecha golpeando dos veces en la mano izquierda y regresa a la altura original',
        },
        {
            phonemes: 'b',
            spelling: phonemes['b'].associated,
            name: 'Vamos',
            nature: 'phoneme',
            category: 'both',
            dificulty: 2,
            description: 'Con la mano derecha a la altura de la cadera y la izquierda a la altura de la barbilla, se realiza un movimiento como corte vertical en sentidos contrarios, la derecha sube a la barbilla y la izquierda baja a la cadera. Por un instante a medio camino ambas manos se rozan',
        },
        {
            phonemes: '-',
            spelling: ['-'],
            name: 'Vamos',
            nature: 'word',
            category: 'both',
            dificulty: 2,
            description: 'Con la mano derecha a la altura de la cadera y la izquierda a la altura de la barbilla, se realiza un movimiento como corte vertical en sentidos contrarios, la derecha sube a la barbilla y la izquierda baja a la cadera. Por un instante a medio camino ambas manos se rozan',
        },
        {
            phonemes: 't',
            spelling: phonemes['t'].associated,
            name: 'Corte',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Con la mano derecha tocando el costado izquierdo de la cadera y la palma viendo hacia abajo, se realiza un corte horizontal hacia la derecha con una pequeña inclinación hacia arriba',
        },
        {
            phonemes: '-',
            spelling: ['-'],
            name: 'Corte',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Con la mano derecha tocando el costado izquierdo de la cadera y la palma viendo hacia abajo, se realiza un corte horizontal hacia la derecha con una pequeña inclinación hacia arriba',
        },
        {
            phonemes: 'd',
            spelling: phonemes['d'].associated,
            name: 'Idear',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Con la palma de la mano derecha entornada a medio camino hacia el pecho y a la altura del corazón, sube tocando con las yemas de los dedos la sección derecha de la frente y luego extiende hacia el frente y ligeramente hacia afuera para terminar con los dedos extendidos apuntando al frente',
        },
        {
            phonemes: '-',
            spelling: ['-'],
            name: 'Idear',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Con la palma de la mano derecha entornada a medio camino hacia el pecho y a la altura del corazón, sube tocando con las yemas de los dedos la sección derecha de la frente y luego extiende hacia el frente y ligeramente hacia afuera para terminar con los dedos extendidos apuntando al frente',
        },
        {
            phonemes: 'k',
            spelling: phonemes['k'].associated,
            name: 'Exclamación',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Con las yemas de los dedos tocándose y las palmas mirando hacia el estómago, se abren los brazos en sentido contrario de manera que las palmas se entornan ligeramente hacia arriba y hacia afuera',
        },
        {
            phonemes: 'dónde',
            spelling: ['dónde'],
            name: 'Exclamación',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Con las yemas de los dedos tocándose y las palmas mirando hacia el estómago, se abren los brazos en sentido contrario de manera que las palmas se entornan ligeramente hacia arriba y hacia afuera',
        },
        {
            phonemes: 'g',
            spelling: phonemes['g'].associated,
            name: 'Medio círculo',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Con las yemas de los dedos tocándose y las palmas mirando hacia adentro a la altura del abdomen, se marca un medio círculo con cada mano para finalizar tocandose las yemas de los dedo otra vez a la altura de la barbilla',
        },
        {
            phonemes: '-',
            spelling: ['-'],
            name: 'Medio círculo',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Con las yemas de los dedos tocándose y las palmas mirando hacia adentro a la altura del abdomen, se marca un medio círculo con cada mano para finalizar tocandose las yemas de los dedo otra vez a la altura de la barbilla',
        },
        {
            phonemes: 'tʃ',
            spelling: phonemes['tʃ'].associated,
            name: 'Aplauso doble',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Con las manos en los costados se realizan 2 aplausos y se termina el movimiento con las manos juntas después del segundo aplauso',
        },
        {
            phonemes: '-',
            spelling: ['-'],
            name: 'Aplauso doble',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Con las manos en los costados se realizan 2 aplausos y se termina el movimiento con las manos juntas después del segundo aplauso',
        },
        {
            phonemes: 'f',
            spelling: phonemes['f'].associated,
            name: 'Chop Chop',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Con la mano a 45 grados y tocando la barbilla se realizan 2 movimientos como cortes hacia al frente',
        },
        {
            phonemes: '-',
            spelling: ['-'],
            name: 'Chop Chop',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Con la mano a 45 grados y tocando la barbilla se realizan 2 movimientos como cortes hacia al frente',
        },
        {
            phonemes: 's',
            spelling: phonemes['s'].associated,
            name: 'Sentimiento',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Tocando con la puntas de los dedos el pecho al nivel del corazón se marca un círculo iniciando a la izquierda',
        },
        {
            phonemes: '-',
            spelling: ['-'],
            name: 'Sentimiento',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Tocando con la puntas de los dedos el pecho al nivel del corazón se marca un círculo iniciando a la izquierda',
        },
        {
            phonemes: 'x',
            spelling: phonemes['x'].associated,
            name: 'Cruzar',
            nature: 'phoneme',
            category: 'phoneme',
            dificulty: 1,
            description: 'Se dibuja una x partiendo de la altura del hombro derecho, después al costado de la cadera izquierda, sube a la altura del hombro izquierdo y finaliza en el costado derecho de la cadera',
        },
        {
            phonemes: 'j',
            spelling: phonemes['j'].associated,
            name: 'Yo',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Con los dedos extendidos y el brazo tocando el bolsillo derecho, se sube el brazo y se toca el pecho a la altura del corazón',
        },
        {
            phonemes: 'io',
            spelling: ['yo'],
            name: 'Yo',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Con los dedos extendidos y el brazo tocando el bolsillo derecho, se sube el brazo y se toca el pecho a la altura del corazón',
        },
        {
            phonemes: 'm',
            spelling: phonemes['m'].associated,
            name: 'Costados',
            nature: 'phoneme',
            category: 'phoneme',
            dificulty: 2,
            description: 'Con la mano apuntando al frente y a la mitad del pecho, se marca un cuarto de arco hacia la izquierda bajando a la altura de las costillas y se regresa con un medio arco a la derecha que sube a la altura del pecho y finaliza en las costillas derechas',
        },
        {
            phonemes: 'n',
            spelling: phonemes['n'].associated,
            name: 'Agitado',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Con la mano a la altura del hombro derecho, se agita dos veces de derecha a izquierda y de regreso',
        },
        {
            phonemes: '-',
            spelling: ['-'],
            name: 'Agitado',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Con la mano a la altura del hombro derecho, se agita dos veces de derecha a izquierda y de regreso',
        },
        {
            phonemes: 'ɲ',
            spelling: phonemes['ɲ'].associated,
            name: 'Medio corazón',
            nature: 'phoneme',
            category: 'both',
            dificulty: 2,
            description: 'Se parte de la mitad del pecho y se realiza un semicírculo hacia afuera a la altura del inicio de las costilla y el hombro, después de baja con una inclinación de 45 grados hacia el ombligo',
        },
        {
            phonemes: '-',
            spelling: ['-'],
            name: 'Medio corazón',
            nature: 'word',
            category: 'both',
            dificulty: 2,
            description: 'Se parte de la mitad del pecho y se realiza un semicírculo hacia afuera a la altura del inicio de las costilla y el hombro, después de baja con una inclinación de 45 grados hacia el ombligo',
        },
        {
            phonemes: 'l',
            spelling: phonemes['l'].associated,
            name: 'Latido doble',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Con la palma tocando el pecho a la altura del corazón, se despega unos centímetros y se vuelve a tocar en 2 ocasiones',
        },
        {
            phonemes: '-',
            spelling: ['-'],
            name: 'Latido doble',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Con la palma tocando el pecho a la altura del corazón, se despega unos centímetros y se vuelve a tocar en 2 ocasiones',
        },
        {
            phonemes: 'ɾ',
            spelling: phonemes['ɾ'].associated,
            name: 'Revolver',
            nature: 'phoneme',
            category: 'both',
            dificulty: 2,
            description: 'Con la mano derecha arriba y la izquierda abajo, se giran en sentidos contrarios(hacia afuera y hacia atrás respectivamente) completando una circunferencia y vuelven a la misma altura en la que se empezó',
        },
        {
            phonemes: '-',
            spelling: ['-'],
            name: 'Revolver',
            nature: 'word',
            category: 'both',
            dificulty: 2,
            description: 'Con la mano derecha arriba y la izquierda abajo, se giran en sentidos contrarios(hacia afuera y hacia atrás respectivamente) completando una circunferencia y vuelven a la misma altura en la que se empezó',
        },
        {
            phonemes: 'r',
            spelling: phonemes['r'].associated,
            name: 'Recorrer',
            nature: 'phoneme',
            category: 'both',
            dificulty: 3,
            description: 'Con la palma mirando al frente y cerca del pecho, se hace un gesto de empujar hacia adelante',
        },
        {
            phonemes: '-',
            spelling: '-',
            name: 'Recorrer',
            nature: 'word',
            category: 'both',
            dificulty: 3,
            description: 'Con la palma mirando al frente y cerca del pecho, se hace un gesto de empujar hacia adelante',
        },
    ]
}